[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_program = "3zQ1ZZSEPG6LeVij4pwsfE4D1RvKjGZvkNvtnzHasSVr"

[programs.devnet]
swap_program = "3zQ1ZZSEPG6LeVij4pwsfE4D1RvKjGZvkNvtnzHasSVr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet"
wallet = "/Users/thanhtranvan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
